name: uellow_reviewers_app
description: Uellow Reviewers — specialists companion app
publish_to: 'none'
version: 1.1.2+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  http: ^1.2.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
